apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: insights-centos
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Convert your operating system from CentOS Linux to RHEL 7
  icon: data:image/s
  