---
apiVersion: v1
kind: Template
metadata:
  name: quickstarts
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: quickstarts
parameters:
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: "1"
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- name: MIN_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/insights-ingress # create quay image
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "false" # can be true?
- description: ClowdEnv Name
  name: ENV_NAME
  value: "quickstarts"
  required: true
