components:
  schemas:
    BadRequest:
      properties:
        msg:
          type: string
      type: object
    NotFound:
      properties:
        msg:
          type: string
      type: object
    v1.HelpTopic:
      properties:
        content:
          format: byte
          type: object
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          nullable: true
          type: string
        groupName:
          type: string
        id:
          minimum: 0
          type: integer
        name:
          type: string
        tags:
          items:
            properties:
              createdAt:
                format: date-time
                type: string
              deletedAt:
                format: date-time
                nullable: true
                type: string
              id:
                minimum: 0
                type: integer
              type:
                type: string
              updatedAt:
                format: date-time
                type: string
              value:
                type: string
            type: object
          type: array
        updatedAt:
          format: date-time
          type: string
      type: object
    v1.Quickstart:
      properties:
        content:
          format: byte
          type: object
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          nullable: true
          type: string
        id:
          minimum: 0
          type: integer
        name:
          type: string
        tags:
          items:
            properties:
              createdAt:
                format: date-time
                type: string
              deletedAt:
                format: date-time
                nullable: true
                type: string
              id:
                minimum: 0
                type: integer
              type:
                type: string
              updatedAt:
                format: date-time
                type: string
              value:
                type: string
            type: object
          type: array
        updatedAt:
          format: date-time
          type: string
      type: object
    v1.QuickstartProgress:
      properties:
        accountId:
          type: integer
        progress:
          format: byte
          type: string
        quickstartName:
          type: string
      type: object
  parameters:
    Bundle:
      name: bundle
      description: If set, content is associated with a specific CRC bundle
      in: query
      required: false
      schema:
        type: string
      explode: true
      style: form
    Application:
      name: application
      description: If set, content is associated with a specific CRC application
      in: query
      required: false
      schema:
        type: string
      explode: true
      style: form
    Name:
      name: name
      description: Search content by name
      in: query
      required: false
      schema:
        type: string
      explode: true
      style: form
    Limit:
      name: limit
      description: Pagination limit
      in: query
      required: false
      schema:
        type: integer
      explode: true
      style: form
    Offset:
      name: offset
      description: Pagination offset
      in: query
      required: false
      schema:
        type: integer
      explode: true
      style: form
    Id:
      name: id
      description: identifier
      in: path
      required: true
      schema:
        type: integer
    TopicName:
      name: name
      description: identifier
      in: path
      required: true
      schema:
        type: string
info:
  license:
    name: MIT
  title: quickstarts
  version: 1.0.0
openapi: 3.0.0
tags:
  - description: A help topic
    name: helptopic
  - description: The content for a quickstart
    name: quickstart
paths:
  /quickstarts:
    get:
      summary: Returns list of all quickstarts
      responses:
        '200':
          description: A JSON array of all quickstarts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/v1.Quickstart'
      parameters:
      - $ref: '#/components/parameters/Bundle'
      - $ref: '#/components/parameters/Application'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'      
      tags:
        - quickstart
  /quickstarts/{id}:
    get:
      summary: Return a quickstarts by ID
      parameters:
      - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: A JSON object with a single quickstart content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Quickstart'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
      tags:
        - quickstart
  /helptopics:
    get:
      summary: Returns list of all help topics
      responses:
        '200':
          description: A JSON array of all help topics
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/v1.HelpTopic'
      parameters:
      - $ref: '#/components/parameters/Bundle'
      - $ref: '#/components/parameters/Application'
      - $ref: '#/components/parameters/Name'
      tags:
        - helptopic
  /helptopics/{name}:
    get:
      summary: Return a help topics set by topic name
      parameters:
      - $ref: '#/components/parameters/TopicName'
      responses:
        '200':
          description: A JSON of a help topic set
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/v1.HelpTopic'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
      tags:
        - helptopic
