info:
  license:
    name: MIT
  title: quickstarts
  version: 1.0.0
openapi: 3.0.0
paths:
  /quickstarts:
    get:
      summary: Returns list of all quickstarts
      responses:
        '200':
          description: A JSON array of all quickstarts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/v1.Quickstart'
      parameters:
      - $ref: '#/components/schemas/queryParams/Bundle'
      - $ref: '#/components/schemas/queryParams/Application'
      - $ref: '#/components/schemas/queryParams/Limit'
      - $ref: '#/components/schemas/queryParams/Offset'      
  /quickstarts/{id}:
    get:
      summary: Return a quickstarts by ID
      responses:
        '200':
          description: A JSON object with a single quickstart content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Quickstart'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
  /helptopics:
    get:
      summary: Returns list of all help topics
      responses:
        '200':
          description: A JSON array of all help topics
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/v1.HelpTopic'
      parameters:
      - $ref: '#/components/schemas/queryParams/Bundle'
      - $ref: '#/components/schemas/queryParams/Application'
      - $ref: '#/components/schemas/queryParams/Name'
  /helptopics/{name}:
    get:
      summary: Return a help topics set by topic name
      responses:
        '200':
          description: A JSON of a help topic set
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/v1.HelpTopic'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'

